"""Add password reset fields to User model

Revision ID: 3093d940eda1
Revises: c5b929fa5a5e
Create Date: 2025-06-30 06:16:02.859903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3093d940eda1'
down_revision = 'c5b929fa5a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Set unique placeholder emails for users with NULL email
    op.execute("UPDATE \"user\" SET email = 'placeholder' || id || '@example.com' WHERE email IS NULL;")
    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.alter_column('biography',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('photo_url',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.create_unique_constraint('uq_user_reset_token', ['reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_reset_token', type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('reset_code')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('family_member', schema=None) as batch_op:
        batch_op.alter_column('photo_url',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('biography',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
